import type { Activity } from "@/lib/activity-types";

const images = {
  cycling: "https://images.unsplash.com/photo-1541625602330-2277a4c46182?auto=format&fit=crop&w=1200&q=85",
  film: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=85",
  market: "https://images.unsplash.com/photo-1533900298318-6b8da08a523e?auto=format&fit=crop&w=1200&q=85",
  quiz: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=1200&q=85",
  heritage: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?auto=format&fit=crop&w=1200&q=85",
  choir: "https://images.unsplash.com/photo-1507838153414-b4b713384a76?auto=format&fit=crop&w=1200&q=85",
  music: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?auto=format&fit=crop&w=1200&q=85",
  children: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=1200&q=85",
  walking: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1200&q=85",
  festival: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=85",
  fair: "https://images.unsplash.com/photo-1513889961551-628c1e5e2ee9?auto=format&fit=crop&w=1200&q=85",
  running: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1200&q=85",
  cafe: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1200&q=85",
  art: "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&w=1200&q=85",
  halloween: "https://images.unsplash.com/photo-1509557965875-b88c97052f0e?auto=format&fit=crop&w=1200&q=85",
  sinterklaas: "https://images.unsplash.com/photo-1512909006721-3d6018887383?auto=format&fit=crop&w=1200&q=85",
  christmas: "https://images.unsplash.com/photo-1512389142860-9c449e58a543?auto=format&fit=crop&w=1200&q=85"
};

export const mockActivities: Activity[] = [
  {
    id: "rabo-dikke-banden-race-sprookjeshof-2026",
    title: "Rabo Dikke Banden Race Sprookjeshof",
    shortDescription: "Gratis fietswedstrijdjes voor kinderen van 2 t/m 12 jaar bij Sprookjeshof.",
    longDescription:
      "Gratis fietswedstrijdjes voor kinderen van 2 t/m 12 jaar in leeftijdsklassen, inclusief loopfietsrace. Toegang tot het park is gratis vanaf 15:00 voor deelnemers en een begeleider.",
    imageUrl: images.cycling,
    startDateTime: "2026-05-13T15:30:00+02:00",
    endDateTime: "2026-05-13T18:00:00+02:00",
    locationName: "Sprookjeshof Zuidlaren",
    address: "Groningerstraat 10, Zuidlaren",
    category: "sport",
    typeTags: ["Kinderen", "Buiten", "Gratis"],
    organizerName: "Ready2Race / Sprookjeshof",
    sourceUrl: "https://www.ready2race.nl/evenementen/rabo-dikke-banden-race-sprookjeshof-zuidlaren2026/",
    indoorOutdoor: "Buiten",
    expectedVisitors: "200-450 personen",
    sourceQuality: "Bevestigd"
  },
  {
    id: "women-only-filmavond-mamma-mia-2026",
    title: "Women Only Filmavond - Mamma Mia!",
    shortDescription: "Filmavond in Grand Cafe Zuidlaren met de musicalfilm Mamma Mia!.",
    longDescription: "Een gezellige filmavond in Grand Cafe Zuidlaren met Mamma Mia!. Horeca-activiteit, publiek toegankelijk via de Grand Cafe-agenda.",
    imageUrl: images.film,
    startDateTime: "2026-05-13T20:00:00+02:00",
    endDateTime: "2026-05-13T22:30:00+02:00",
    locationName: "Grand Cafe Zuidlaren",
    address: "De Millystraat 8, Zuidlaren",
    category: "cultuur",
    typeTags: ["Binnen", "Betaald"],
    organizerName: "Grand Cafe Zuidlaren",
    sourceUrl: "https://grandcafezuidlaren.nl/",
    indoorOutdoor: "Binnen",
    expectedVisitors: "30-100 personen",
    sourceQuality: "Bevestigd"
  },
  {
    id: "braderie-rommelmarkt-14-mei-2026",
    title: "Braderie & rommelmarkt",
    shortDescription: "Publieke braderie en rommelmarkt op De Brink met kramen en rondloopbezoek.",
    longDescription: "Publieke braderie en rommelmarkt op De Brink. Een lokale marktactiviteit met verkoopkramen, rondloopbezoek en een dorps karakter.",
    imageUrl: images.market,
    startDateTime: "2026-05-14T10:00:00+02:00",
    endDateTime: "2026-05-14T16:30:00+02:00",
    locationName: "De Brink, Zuidlaren",
    category: "markt",
    typeTags: ["Buiten", "Gratis"],
    organizerName: "Lokale marktorganisatie",
    sourceUrl: "https://brinkhotel.nl/nl/p/zuidlaren/markten-en-braderieen",
    indoorOutdoor: "Buiten",
    expectedVisitors: "1.000-4.000 bezoekers",
    sourceQuality: "Aangemeld evenement"
  },
  {
    id: "concert-tijdreis-zuidlaarder-mannenkoor-2026",
    title: "Concert Tijdreis",
    shortDescription: "Koor- en samenzangconcert door het Christelijk Zuidlaarder Mannenkoor.",
    longDescription:
      "Koor- en samenzangconcert door het Christelijk Zuidlaarder Mannenkoor. Het programma neemt bezoekers mee van schepping tot wederkomst met klassieke en moderne liederen. Dirigent: Marnix Onrust.",
    imageUrl: images.choir,
    startDateTime: "2026-05-14T19:30:00+02:00",
    endDateTime: "2026-05-14T22:00:00+02:00",
    locationName: "NGK De Kandelaar",
    address: "Schipborgerweg 45a, Zuidlaren",
    category: "cultuur",
    typeTags: ["Binnen", "Concert", "Koor"],
    organizerName: "Christelijk Zuidlaarder Mannenkoor",
    sourceUrl: "https://www.chr-zuidlaardermannenkoor.nl/agenda.htm",
    indoorOutdoor: "Binnen",
    expectedVisitors: "150-250 bezoekers",
    sourceQuality: "Hard bevestigd"
  },
  {
    id: "pub-quiz-grand-cafe-15-mei-2026",
    title: "Pub Quiz",
    shortDescription: "Pubquiz in Grand Cafe Zuidlaren voor teams en liefhebbers van trivia.",
    longDescription: "Pubquiz in lokale horeca. Publiek toegankelijk via Grand Cafe Zuidlaren; exacte teamcapaciteit is niet gepubliceerd.",
    imageUrl: images.quiz,
    startDateTime: "2026-05-15T20:00:00+02:00",
    endDateTime: "2026-05-15T22:30:00+02:00",
    locationName: "Grand Cafe Zuidlaren",
    address: "De Millystraat 8, Zuidlaren",
    category: "cultuur",
    typeTags: ["Binnen", "Horeca"],
    organizerName: "Grand Cafe Zuidlaren",
    sourceUrl: "https://grandcafezuidlaren.nl/",
    indoorOutdoor: "Binnen",
    expectedVisitors: "30-100 personen",
    sourceQuality: "Bevestigd"
  },
  {
    id: "stoomdagen-de-wachter-2026",
    title: "Stoomdagen en show stationaire motoren",
    shortDescription: "Techniek- en erfgoedevenement bij Molenmuseum De Wachter.",
    longDescription: "Techniek- en erfgoedevenement bij De Wachter met stoom en stationaire motoren. Publiek evenement voor liefhebbers van historische techniek.",
    imageUrl: images.heritage,
    startDateTime: "2026-05-16T10:00:00+02:00",
    endDateTime: "2026-05-16T17:00:00+02:00",
    locationName: "Molenmuseum De Wachter",
    address: "Havenstraat 36, Zuidlaren",
    category: "cultuur",
    typeTags: ["Erfgoed", "Familie", "Gemengd"],
    organizerName: "OTMV Drenthe / De Wachter",
    sourceUrl: "https://www.otmv.nl/drenthe/locaties/de-wachter-zuidlaren/",
    indoorOutdoor: "Gemengd",
    expectedVisitors: "200-800 bezoekers",
    sourceQuality: "Bevestigd"
  },
  {
    id: "social-only-horeca-events-zuidlaren-monitor-2026",
    title: "Kortcyclische horeca-events Zuidlaren",
    shortDescription: "Monitor-item voor social-only live muziek, dj-avonden en thema-avonden bij lokale cafés.",
    longDescription:
      "Monitor-item voor kortcyclische horeca-events bij onder meer Café De Vliegh, Café De Paris, Café Boschhuis en Klasbak. Deze activiteiten worden vaak via sociale media aangekondigd en krijgen daarom alvast een zichtbare monitorplek.",
    imageUrl: images.cafe,
    startDateTime: "2026-05-30T21:00:00+02:00",
    endDateTime: "2026-05-31T01:00:00+02:00",
    locationName: "Diverse horecalocaties Zuidlaren",
    category: "muziek",
    typeTags: ["Monitor", "Horeca", "Live muziek"],
    organizerName: "Lokale horecaondernemers",
    sourceUrl: "https://www.uitagenda.nl/zuidlaren",
    indoorOutdoor: "Binnen",
    expectedVisitors: "50-250 bezoekers per avond",
    sourceQuality: "Monitor-item, datum indicatief"
  },
  {
    id: "open-muziek-podium-grand-cafe-4-juni-2026",
    title: "Open Muziek Podium",
    shortDescription: "Open podium voor muzikanten en muziekliefhebbers in Grand Cafe Zuidlaren.",
    longDescription:
      "Terugkerend open podium voor muzikanten en muziekliefhebbers. Grand Cafe noemt de formule elke eerste donderdag van de maand; deze datum is als monitor-item toegevoegd.",
    imageUrl: images.music,
    startDateTime: "2026-06-04T20:00:00+02:00",
    endDateTime: "2026-06-04T23:30:00+02:00",
    locationName: "Grand Cafe Zuidlaren",
    address: "De Millystraat 8, Zuidlaren",
    category: "muziek",
    typeTags: ["Monitor", "Binnen", "Open podium"],
    organizerName: "Grand Cafe Zuidlaren",
    sourceUrl: "https://grandcafezuidlaren.nl/nieuws/nieuw-open-muziek-podium/",
    indoorOutdoor: "Binnen",
    expectedVisitors: "30-120 bezoekers/deelnemers",
    sourceQuality: "Monitor-item, reeks bevestigd"
  },
  {
    id: "greymen-coverband-live-2026",
    title: "Greymen coverband live",
    shortDescription: "Live optreden met covers van U2, Golden Earring, De Dijk en meer.",
    longDescription: "Live optreden van coverband Greymen met covers van onder andere U2, Golden Earring, De Dijk, Herman Brood en Kool & The Gang.",
    imageUrl: images.music,
    startDateTime: "2026-05-17T16:00:00+02:00",
    endDateTime: "2026-05-17T18:30:00+02:00",
    locationName: "Grand Cafe Zuidlaren",
    category: "muziek",
    typeTags: ["Binnen", "Horeca", "Betaald"],
    organizerName: "Grand Cafe Zuidlaren",
    sourceUrl: "https://grandcafezuidlaren.nl/",
    indoorOutdoor: "Binnen",
    expectedVisitors: "80-200 bezoekers",
    sourceQuality: "Bevestigd"
  },
  {
    id: "cape-kroon-festival-2026",
    title: "Cape & Kroon Festival",
    shortDescription: "Kinderfestival rond fantasie, helden, ridders en prinsessen.",
    longDescription: "Kinderfestival in Bibliotheek Zuidlaren rond fantasie, helden, ridders en prinsessen. Gericht op jonge kinderen en gezinnen.",
    imageUrl: images.children,
    startDateTime: "2026-05-23T10:30:00+02:00",
    endDateTime: "2026-05-23T13:00:00+02:00",
    locationName: "Bibliotheek Zuidlaren",
    address: "Middenstraat 1, Zuidlaren",
    category: "kinderen",
    typeTags: ["Binnen", "Familie"],
    organizerName: "Bibliotheek Zuidlaren",
    sourceUrl: "https://naarzuidlaren.nl/evenementen/cape-kroon-festival/",
    indoorOutdoor: "Binnen",
    expectedVisitors: "50-250 bezoekers",
    sourceQuality: "Bevestigd"
  },
  {
    id: "spill-the-beans-live-2026",
    title: "Spill the Beans live",
    shortDescription: "Zondagmiddag live muziek met covers van pop, soul en funk.",
    longDescription: "Live optreden met covers van onder andere Michael Jackson, Sting, Chic, Sister Sledge en Stevie Wonder.",
    imageUrl: images.music,
    startDateTime: "2026-05-24T16:00:00+02:00",
    endDateTime: "2026-05-24T18:30:00+02:00",
    locationName: "Grand Cafe Zuidlaren",
    category: "muziek",
    typeTags: ["Binnen", "Horeca", "Betaald"],
    organizerName: "Grand Cafe Zuidlaren",
    sourceUrl: "https://grandcafezuidlaren.nl/",
    indoorOutdoor: "Binnen",
    expectedVisitors: "80-200 bezoekers",
    sourceQuality: "Bevestigd, datumconflict"
  },
  {
    id: "hondsrugmarkt-pinkstermarkt-2026",
    title: "Hondsrugmarkt / Pinkstermarkt",
    shortDescription: "Braderie en vlooienmarkt op De Brink met vrije toegang.",
    longDescription: "Hondsrugmarkt op De Brink: combinatie van braderie en vlooienmarkt. Vrije toegang en een groot aanbod aan kramen.",
    imageUrl: images.market,
    startDateTime: "2026-05-25T10:00:00+02:00",
    endDateTime: "2026-05-25T16:30:00+02:00",
    locationName: "De Brink, Zuidlaren",
    category: "markt",
    typeTags: ["Buiten", "Gratis"],
    organizerName: "Vitalis Markten",
    sourceUrl: "https://www.vitalismarkten.nl/hondsrugmarkten",
    indoorOutdoor: "Buiten",
    expectedVisitors: "2.000-6.000 bezoekers",
    sourceQuality: "Bevestigd"
  },
  {
    id: "contradiction-live-2026",
    title: "Contradiction live",
    shortDescription: "Zondagmiddag live muziek in Grand Cafe Zuidlaren.",
    longDescription: "Live muziek in Grand Cafe Zuidlaren. Entree volgens de officiele agenda: 6 euro.",
    imageUrl: images.music,
    startDateTime: "2026-05-31T16:00:00+02:00",
    endDateTime: "2026-05-31T18:30:00+02:00",
    locationName: "Grand Cafe Zuidlaren",
    category: "muziek",
    typeTags: ["Binnen", "Horeca", "Betaald"],
    organizerName: "Grand Cafe Zuidlaren",
    sourceUrl: "https://grandcafezuidlaren.nl/",
    indoorOutdoor: "Binnen",
    expectedVisitors: "80-200 bezoekers",
    sourceQuality: "Bevestigd"
  },
  {
    id: "avondvierdaagse-zuidlaren-2026",
    title: "Avondvierdaagse Zuidlaren",
    shortDescription: "Vier avonden wandelen met routes van 5 en 10 kilometer.",
    longDescription: "Vierdaags wandelevenement met 5 en 10 kilometer routes voor kinderen, gezinnen en volwassenen. Vrijdag is traditioneel de intocht en afronding.",
    imageUrl: images.walking,
    startDateTime: "2026-06-02T17:45:00+02:00",
    endDateTime: "2026-06-05T21:00:00+02:00",
    locationName: "In en om Zuidlaren",
    category: "sport",
    typeTags: ["Buiten", "Familie", "Wandelen"],
    organizerName: "Stichting Avondvierdaagse Zuidlaren",
    sourceUrl: "https://www.avondvierdaagsezuidlaren.nl/",
    indoorOutdoor: "Buiten",
    expectedVisitors: "800-1.500 deelnemers plus publiek",
    sourceQuality: "Bevestigd"
  },
  {
    id: "sugar-mama-live-2026",
    title: "Sugar Mama live",
    shortDescription: "Blues, boogie, rock-'n-roll en roots in Grand Cafe Zuidlaren.",
    longDescription: "Live optreden van Sugar Mama met blues, boogie, rock-'n-roll en roots. Entree volgens bron: 6 euro.",
    imageUrl: images.music,
    startDateTime: "2026-06-07T16:00:00+02:00",
    endDateTime: "2026-06-07T18:30:00+02:00",
    locationName: "Grand Cafe Zuidlaren",
    category: "muziek",
    typeTags: ["Binnen", "Horeca", "Betaald"],
    organizerName: "Grand Cafe Zuidlaren",
    sourceUrl: "https://grandcafezuidlaren.nl/",
    indoorOutdoor: "Binnen",
    expectedVisitors: "80-200 bezoekers",
    sourceQuality: "Bevestigd"
  },
  {
    id: "tienkamp-expeditie-zuidlaren-2026",
    title: "Tienkamp Zuidlaren - Expeditie Zuidlaren",
    shortDescription: "Sport-, spel- en denkactiviteiten door het centrum van Zuidlaren.",
    longDescription: "17e editie van Tienkamp Zuidlaren met sport-, spel- en denkactiviteiten door het centrum. Thema: Expeditie Zuidlaren.",
    imageUrl: images.festival,
    startDateTime: "2026-06-12T19:00:00+02:00",
    endDateTime: "2026-06-12T23:00:00+02:00",
    locationName: "Centrum Zuidlaren",
    category: "sport",
    typeTags: ["Buiten", "Dorpsactiviteit", "Horeca"],
    organizerName: "Tienkamp Zuidlaren",
    sourceUrl: "https://naarzuidlaren.nl/evenementen/tienkamp/",
    indoorOutdoor: "Buiten",
    expectedVisitors: "300-800 personen",
    sourceQuality: "Bevestigd"
  },
  {
    id: "braderie-rommelmarkt-14-juni-2026",
    title: "Braderie & rommelmarkt",
    shortDescription: "Publieke braderie en rommelmarkt op De Brink.",
    longDescription: "Publieke braderie en rommelmarkt op De Brink met verkoopkramen en rondloopbezoek.",
    imageUrl: images.market,
    startDateTime: "2026-06-14T10:00:00+02:00",
    endDateTime: "2026-06-14T16:30:00+02:00",
    locationName: "De Brink, Zuidlaren",
    category: "markt",
    typeTags: ["Buiten", "Gratis"],
    organizerName: "Lokale marktorganisatie",
    sourceUrl: "https://brinkhotel.nl/nl/p/zuidlaren/markten-en-braderieen",
    indoorOutdoor: "Buiten",
    expectedVisitors: "1.000-4.000 bezoekers",
    sourceQuality: "Aangemeld evenement"
  },
  {
    id: "groove-ally-live-2026",
    title: "Groove Ally live",
    shortDescription: "Meerstemmig live optreden in Grand Cafe Zuidlaren.",
    longDescription: "Live optreden van Groove Ally. De officiele agenda omschrijft de band als muzikaal en meerstemmig.",
    imageUrl: images.music,
    startDateTime: "2026-06-14T16:00:00+02:00",
    endDateTime: "2026-06-14T18:30:00+02:00",
    locationName: "Grand Cafe Zuidlaren",
    category: "muziek",
    typeTags: ["Binnen", "Horeca", "Betaald"],
    organizerName: "Grand Cafe Zuidlaren",
    sourceUrl: "https://grandcafezuidlaren.nl/",
    indoorOutdoor: "Binnen",
    expectedVisitors: "80-200 bezoekers",
    sourceQuality: "Bevestigd"
  },
  {
    id: "vaderdagactiviteit-centrum-zuidlaren-2026",
    title: "Vaderdagactiviteit centrum Zuidlaren",
    shortDescription: "Kinderen zoeken mini-Berend Botjes bij ondernemers in het centrum.",
    longDescription: "Publieke winkelcentrumactiviteit rond Vaderdag. Kinderen kunnen op jacht naar mini-Berend Botjes bij ondernemers in Zuidlaren.",
    imageUrl: images.children,
    startDateTime: "2026-06-20T10:00:00+02:00",
    endDateTime: "2026-06-20T16:00:00+02:00",
    locationName: "Centrum Zuidlaren",
    category: "kinderen",
    typeTags: ["Buiten", "Familie", "Winkels"],
    organizerName: "Lokale ondernemers Zuidlaren",
    sourceUrl: "https://naarzuidlaren.nl/evenementen/vaderdag/",
    indoorOutdoor: "Gemengd",
    expectedVisitors: "200-800 bezoekers",
    sourceQuality: "Bevestigd"
  },
  {
    id: "hondsrugmarkt-21-juni-2026",
    title: "Hondsrugmarkt",
    shortDescription: "Braderie en vlooienmarkt op De Brink met vrije toegang.",
    longDescription: "Hondsrugmarkt op De Brink: braderie en vlooienmarkt met vrije toegang.",
    imageUrl: images.market,
    startDateTime: "2026-06-21T10:00:00+02:00",
    endDateTime: "2026-06-21T16:30:00+02:00",
    locationName: "De Brink, Zuidlaren",
    category: "markt",
    typeTags: ["Buiten", "Gratis"],
    organizerName: "Vitalis Markten",
    sourceUrl: "https://www.vitalismarkten.nl/hondsrugmarkten",
    indoorOutdoor: "Buiten",
    expectedVisitors: "2.000-6.000 bezoekers",
    sourceQuality: "Bevestigd"
  },
  {
    id: "berend-botje-festival-2026",
    title: "Berend Botje Festival",
    shortDescription: "Dorpsfestival rond Berend Botje in het centrum van Zuidlaren.",
    longDescription: "Dorpsfestival rond Berend Botje. Eerdere beschrijvingen noemen kinderen, muziek, theater, sportiviteit en eten.",
    imageUrl: images.festival,
    startDateTime: "2026-06-26T10:00:00+02:00",
    endDateTime: "2026-06-27T22:00:00+02:00",
    locationName: "Centrum Zuidlaren",
    category: "cultuur",
    typeTags: ["Buiten", "Familie", "Festival"],
    organizerName: "Lokale evenementenorganisatie",
    sourceUrl: "https://naarzuidlaren.nl/berend-botje-festival/",
    indoorOutdoor: "Buiten",
    expectedVisitors: "2.000-8.000 bezoekers",
    sourceQuality: "Datum bevestigd, programma volgt"
  },
  {
    id: "hondsrugmarkt-12-juli-2026",
    title: "Hondsrugmarkt",
    shortDescription: "Zomerse braderie en vlooienmarkt op De Brink.",
    longDescription: "Hondsrugmarkt op De Brink: braderie en vlooienmarkt met vrije toegang.",
    imageUrl: images.market,
    startDateTime: "2026-07-12T10:00:00+02:00",
    endDateTime: "2026-07-12T16:30:00+02:00",
    locationName: "De Brink, Zuidlaren",
    category: "markt",
    typeTags: ["Buiten", "Gratis"],
    organizerName: "Vitalis Markten",
    sourceUrl: "https://www.vitalismarkten.nl/hondsrugmarkten",
    indoorOutdoor: "Buiten",
    expectedVisitors: "2.000-6.000 bezoekers",
    sourceQuality: "Bevestigd"
  },
  {
    id: "braderie-rommelmarkt-19-juli-2026",
    title: "Braderie & rommelmarkt",
    shortDescription: "Publieke braderie en rommelmarkt op De Brink.",
    longDescription: "Publieke braderie en rommelmarkt op De Brink met kramen en rondloopbezoek.",
    imageUrl: images.market,
    startDateTime: "2026-07-19T10:00:00+02:00",
    endDateTime: "2026-07-19T16:30:00+02:00",
    locationName: "De Brink, Zuidlaren",
    category: "markt",
    typeTags: ["Buiten", "Gratis"],
    organizerName: "Lokale marktorganisatie",
    sourceUrl: "https://brinkhotel.nl/nl/p/zuidlaren/markten-en-braderieen",
    indoorOutdoor: "Buiten",
    expectedVisitors: "1.000-4.000 bezoekers",
    sourceQuality: "Aangemeld evenement"
  },
  {
    id: "hondsrugmarkt-23-juli-2026",
    title: "Hondsrugmarkt",
    shortDescription: "Donderdagmarkt op De Brink met braderie en vlooienmarkt.",
    longDescription: "Hondsrugmarkt op De Brink: braderie en vlooienmarkt met vrije toegang. Let op: 23 juli 2026 is donderdag.",
    imageUrl: images.market,
    startDateTime: "2026-07-23T10:00:00+02:00",
    endDateTime: "2026-07-23T16:30:00+02:00",
    locationName: "De Brink, Zuidlaren",
    category: "markt",
    typeTags: ["Buiten", "Gratis"],
    organizerName: "Vitalis Markten",
    sourceUrl: "https://www.vitalismarkten.nl/hondsrugmarkten",
    indoorOutdoor: "Buiten",
    expectedVisitors: "2.000-6.000 bezoekers",
    sourceQuality: "Bevestigd"
  },
  {
    id: "hondsrugmarkt-30-juli-2026",
    title: "Hondsrugmarkt",
    shortDescription: "Zomerse markt op De Brink met braderie en vlooienmarkt.",
    longDescription: "Hondsrugmarkt op De Brink: braderie en vlooienmarkt met vrije toegang.",
    imageUrl: images.market,
    startDateTime: "2026-07-30T10:00:00+02:00",
    endDateTime: "2026-07-30T16:30:00+02:00",
    locationName: "De Brink, Zuidlaren",
    category: "markt",
    typeTags: ["Buiten", "Gratis"],
    organizerName: "Vitalis Markten",
    sourceUrl: "https://www.vitalismarkten.nl/hondsrugmarkten",
    indoorOutdoor: "Buiten",
    expectedVisitors: "2.000-6.000 bezoekers",
    sourceQuality: "Bevestigd"
  },
  {
    id: "markt-van-melk-en-honing-2026",
    title: "Markt van Melk en Honing",
    shortDescription: "Themamarkt rond natuur, buitenleven en imkerij op de Grote Brink.",
    longDescription:
      "40e editie van de Markt van Melk en Honing. Thema's: natuur, milieu, buitenleven en imkerij. Circa 100 standhouders, demonstraties, muziek en kinderactiviteiten.",
    imageUrl: images.market,
    startDateTime: "2026-08-01T10:00:00+02:00",
    endDateTime: "2026-08-01T16:00:00+02:00",
    locationName: "Grote Brink, Zuidlaren",
    category: "natuur",
    typeTags: ["Buiten", "Familie", "Gratis"],
    organizerName: "Imkervereniging Zuidlaren",
    sourceUrl: "https://www.marktvanmelkenhoning.nl/",
    indoorOutdoor: "Buiten",
    expectedVisitors: "3.000-10.000 bezoekers",
    sourceQuality: "Bevestigd"
  },
  {
    id: "kinderdorp-zuidlaren-2026",
    title: "Kinderdorp Zuidlaren",
    shortDescription: "Grote jaarlijkse speelweek voor kinderen van 7 t/m 12 jaar.",
    longDescription: "Grote jaarlijkse kinder-speelweek. Kinderen bouwen en spelen gedurende de week; vrijdagmiddag is het terrein voor publiek toegankelijk.",
    imageUrl: images.children,
    startDateTime: "2026-08-03T09:00:00+02:00",
    endDateTime: "2026-08-07T16:00:00+02:00",
    locationName: "Parkeerterrein FC Zuidlaren",
    address: "Randweg 3, Zuidlaren",
    category: "kinderen",
    typeTags: ["Buiten", "Kinderweek"],
    organizerName: "Stichting Kinderdorp Zuidlaren",
    sourceUrl: "https://www.kinderdorpzuidlaren.nl/",
    indoorOutdoor: "Buiten",
    expectedVisitors: "Maximaal 350 kinderen",
    sourceQuality: "Bevestigd"
  },
  {
    id: "hondsrugmarkt-6-augustus-2026",
    title: "Hondsrugmarkt",
    shortDescription: "Braderie en vlooienmarkt op De Brink met vrije toegang.",
    longDescription: "Hondsrugmarkt op De Brink: braderie en vlooienmarkt met vrije toegang.",
    imageUrl: images.market,
    startDateTime: "2026-08-06T10:00:00+02:00",
    endDateTime: "2026-08-06T16:30:00+02:00",
    locationName: "De Brink, Zuidlaren",
    category: "markt",
    typeTags: ["Buiten", "Gratis"],
    organizerName: "Vitalis Markten",
    sourceUrl: "https://www.vitalismarkten.nl/hondsrugmarkten",
    indoorOutdoor: "Buiten",
    expectedVisitors: "2.000-6.000 bezoekers",
    sourceQuality: "Bevestigd"
  },
  {
    id: "braderie-rommelmarkt-16-augustus-2026",
    title: "Braderie & rommelmarkt",
    shortDescription: "Publieke braderie en rommelmarkt op De Brink.",
    longDescription: "Publieke braderie en rommelmarkt op De Brink met verkoopkramen en rondloopbezoek.",
    imageUrl: images.market,
    startDateTime: "2026-08-16T10:00:00+02:00",
    endDateTime: "2026-08-16T16:30:00+02:00",
    locationName: "De Brink, Zuidlaren",
    category: "markt",
    typeTags: ["Buiten", "Gratis"],
    organizerName: "Lokale marktorganisatie",
    sourceUrl: "https://brinkhotel.nl/nl/p/zuidlaren/markten-en-braderieen",
    indoorOutdoor: "Buiten",
    expectedVisitors: "1.000-4.000 bezoekers",
    sourceQuality: "Aangemeld evenement"
  },
  {
    id: "braderie-rommelmarkt-30-augustus-2026",
    title: "Braderie & rommelmarkt",
    shortDescription: "Publieke braderie en rommelmarkt op De Brink.",
    longDescription: "Publieke braderie en rommelmarkt op De Brink met verkoopkramen en rondloopbezoek.",
    imageUrl: images.market,
    startDateTime: "2026-08-30T10:00:00+02:00",
    endDateTime: "2026-08-30T16:30:00+02:00",
    locationName: "De Brink, Zuidlaren",
    category: "markt",
    typeTags: ["Buiten", "Gratis"],
    organizerName: "Lokale marktorganisatie",
    sourceUrl: "https://brinkhotel.nl/nl/p/zuidlaren/markten-en-braderieen",
    indoorOutdoor: "Buiten",
    expectedVisitors: "1.000-4.000 bezoekers",
    sourceQuality: "Aangemeld evenement"
  },
  {
    id: "braderie-rommelmarkt-13-september-2026",
    title: "Braderie & rommelmarkt",
    shortDescription: "Publieke braderie en rommelmarkt op De Brink.",
    longDescription: "Publieke braderie en rommelmarkt op De Brink met verkoopkramen en rondloopbezoek.",
    imageUrl: images.market,
    startDateTime: "2026-09-13T10:00:00+02:00",
    endDateTime: "2026-09-13T16:30:00+02:00",
    locationName: "De Brink, Zuidlaren",
    category: "markt",
    typeTags: ["Buiten", "Gratis"],
    organizerName: "Lokale marktorganisatie",
    sourceUrl: "https://brinkhotel.nl/nl/p/zuidlaren/markten-en-braderieen",
    indoorOutdoor: "Buiten",
    expectedVisitors: "1.000-4.000 bezoekers",
    sourceQuality: "Aangemeld evenement"
  },
  {
    id: "hunzeloopwandeltocht-2026",
    title: "Hunzeloopwandeltocht",
    shortDescription: "Wandeltocht door het Drentse landschap met routes van 2,5 tot 25 km.",
    longDescription: "Wandeltocht door het Drentse landschap met routes van 2,5, 5, 10, 15, 20 en 25 kilometer. Natuur, cultuur en gezelligheid staan centraal.",
    imageUrl: images.walking,
    startDateTime: "2026-09-19T08:00:00+02:00",
    endDateTime: "2026-09-19T17:00:00+02:00",
    locationName: "Het Achterom, Zuidlaren",
    category: "natuur",
    typeTags: ["Buiten", "Wandelen", "Sport"],
    organizerName: "Hunzeloopwandeltocht",
    sourceUrl: "https://www.hunzeloopwandeltocht.nl/",
    indoorOutdoor: "Buiten",
    expectedVisitors: "500-1.500 deelnemers/toeschouwers",
    sourceQuality: "Bevestigd"
  },
  {
    id: "festival-vitaal-2026",
    title: "Festival Vitaal",
    shortDescription: "Dag rond sport, gezondheid, welzijn en cultuur in het centrum.",
    longDescription: "Dag in het centrum rond sport, gezondheid, welzijn en cultuur, aansluitend op de Hunzeloop. Het detailprogramma volgt nog.",
    imageUrl: images.festival,
    startDateTime: "2026-09-19T12:00:00+02:00",
    endDateTime: "2026-09-19T17:00:00+02:00",
    locationName: "Brinkje bij De Vlindertuin",
    category: "sport",
    typeTags: ["Buiten", "Welzijn", "Cultuur"],
    organizerName: "Gemeente Tynaarlo / Sport Tynaarlo",
    sourceUrl: "https://www.tynaarlo.nl/sociaalteam/sport-en-gezondheid/festival-vitaal",
    indoorOutdoor: "Buiten",
    expectedVisitors: "500-2.000 bezoekers",
    sourceQuality: "Datum bevestigd, programma volgt"
  },
  {
    id: "fietsfestival-zuidlaren-2026",
    title: "Fietsfestival Zuidlaren",
    shortDescription: "Fietsfestival voor jong en oud met sportieve activiteiten.",
    longDescription: "Fietsfestival voor jong en oud. Eerdere informatie noemt loopfiets- en dikke-bandenraces, MTB-clinics en wielerwedstrijden.",
    imageUrl: images.cycling,
    startDateTime: "2026-09-19T10:00:00+02:00",
    endDateTime: "2026-09-19T17:00:00+02:00",
    locationName: "In en om Zuidlaren",
    category: "sport",
    typeTags: ["Buiten", "Fietsen", "Familie"],
    organizerName: "Fietsfestival Zuidlaren",
    sourceUrl: "https://www.fietsfestivalzuidlaren.nl/",
    indoorOutdoor: "Buiten",
    expectedVisitors: "300-1.500 deelnemers/bezoekers",
    sourceQuality: "Datum bevestigd, programma volgt"
  },
  {
    id: "hondsrugmarkt-20-september-2026",
    title: "Hondsrugmarkt",
    shortDescription: "Braderie en vlooienmarkt op De Brink met vrije toegang.",
    longDescription: "Hondsrugmarkt op De Brink: braderie en vlooienmarkt met vrije toegang.",
    imageUrl: images.market,
    startDateTime: "2026-09-20T10:00:00+02:00",
    endDateTime: "2026-09-20T16:30:00+02:00",
    locationName: "De Brink, Zuidlaren",
    category: "markt",
    typeTags: ["Buiten", "Gratis"],
    organizerName: "Vitalis Markten",
    sourceUrl: "https://www.vitalismarkten.nl/hondsrugmarkten",
    indoorOutdoor: "Buiten",
    expectedVisitors: "2.000-6.000 bezoekers",
    sourceQuality: "Bevestigd"
  },
  {
    id: "kermis-zuidlaardermarkt-2026",
    title: "Kermis Zuidlaardermarkt",
    shortDescription: "Kermis tijdens de Zuidlaardermarktweek op De Brink.",
    longDescription: "Kermis tijdens de Zuidlaardermarktweek. Onderdeel van de bredere feestweek met randactiviteiten, horeca, muziek en markt.",
    imageUrl: images.fair,
    startDateTime: "2026-10-16T18:00:00+02:00",
    endDateTime: "2026-10-21T20:00:00+02:00",
    locationName: "De Brink, Zuidlaren",
    category: "cultuur",
    typeTags: ["Buiten", "Kermis", "Feestweek"],
    organizerName: "Gemeente Tynaarlo / SEZ",
    sourceUrl: "https://www.tynaarlo.nl/zuidlaardermarkt/programma",
    indoorOutdoor: "Buiten",
    expectedVisitors: "Duizenden over de week",
    sourceQuality: "Bevestigd, programma volgt"
  },
  {
    id: "randactiviteiten-zuidlaardermarkt-2026",
    title: "Randactiviteiten Zuidlaardermarkt",
    shortDescription: "Feestweekprogramma met muziek, horeca, cultuur en kinderactiviteiten.",
    longDescription: "Randprogramma rond de Zuidlaardermarkt met kermis, hardlopen, kinderactiviteiten, vuurwerk, live muziek en straattheater. Programma 2026 volgt.",
    imageUrl: images.festival,
    startDateTime: "2026-10-16T18:00:00+02:00",
    endDateTime: "2026-10-20T23:00:00+02:00",
    locationName: "Centrum Zuidlaren",
    category: "cultuur",
    typeTags: ["Gemengd", "Feestweek", "Horeca"],
    organizerName: "Stichting Evenementen Zuidlaardermarkt",
    sourceUrl: "https://www.evenementenzuidlaardermarkt.nl/",
    indoorOutdoor: "Gemengd",
    expectedVisitors: "Duizenden over de week",
    sourceQuality: "Datum bevestigd, programma volgt"
  },
  {
    id: "opening-kermis-zuidlaardermarkt-2026",
    title: "Opening kermis Zuidlaardermarkt",
    shortDescription: "Formele opening van de kermis tijdens Zuidlaardermarktweek.",
    longDescription: "Formele opening van de kermis als onderdeel van de Zuidlaardermarktweek. Exacte tijd volgt via gemeente of programma.",
    imageUrl: images.fair,
    startDateTime: "2026-10-17T13:00:00+02:00",
    endDateTime: "2026-10-17T14:00:00+02:00",
    locationName: "De Brink / centrum Zuidlaren",
    category: "cultuur",
    typeTags: ["Buiten", "Kermis", "Feestweek"],
    organizerName: "Gemeente Tynaarlo / SEZ",
    sourceUrl: "https://www.tynaarlo.nl/zuidlaardermarkt/programma",
    indoorOutdoor: "Buiten",
    expectedVisitors: "500-2.000 aanwezigen",
    sourceQuality: "Bevestigd, tijd volgt"
  },
  {
    id: "zuidlaardermarktloop-2026",
    title: "Zuidlaardermarktloop",
    shortDescription: "Hardloopwedstrijd tijdens de Zuidlaardermarktweek.",
    longDescription: "Hardloopwedstrijd tijdens de Zuidlaardermarktweek. Gemeente verwijst voor meer informatie naar Loopgroep Drentsche Aa.",
    imageUrl: images.running,
    startDateTime: "2026-10-18T10:00:00+02:00",
    endDateTime: "2026-10-18T13:00:00+02:00",
    locationName: "Zuidlaren",
    category: "sport",
    typeTags: ["Buiten", "Hardlopen", "Feestweek"],
    organizerName: "Loopgroep Drentsche Aa",
    sourceUrl: "https://www.loopgroepdrentscheaa.nl/",
    indoorOutdoor: "Buiten",
    expectedVisitors: "300-1.500 deelnemers/toeschouwers",
    sourceQuality: "Bevestigd"
  },
  {
    id: "nacht-van-zuidlaren-2026",
    title: "Nacht van Zuidlaren",
    shortDescription: "Traditionele uitgaansnacht voorafgaand aan de Zuidlaardermarkt.",
    longDescription: "Traditionele uitgaansnacht voorafgaand aan de Zuidlaardermarkt met live muziek in feesttent en horeca en kermis in de avond/nacht.",
    imageUrl: images.music,
    startDateTime: "2026-10-19T20:00:00+02:00",
    endDateTime: "2026-10-20T02:00:00+02:00",
    locationName: "Centrum Zuidlaren",
    category: "muziek",
    typeTags: ["Gemengd", "Horeca", "Feestweek"],
    organizerName: "SEZ en lokale horeca",
    sourceUrl: "https://brinkhotel.nl/nl/p/zuidlaardermarkt",
    indoorOutdoor: "Gemengd",
    expectedVisitors: "Duizenden bezoekers",
    sourceQuality: "Traditie bevestigd, detailprogramma volgt"
  },
  {
    id: "zuidlaardermarkt-2026",
    title: "Zuidlaardermarkt",
    shortDescription: "Grote paardenmarkt, warenmarkt, eetkramen en kermis in het centrum.",
    longDescription: "Oudste/grootste paardenmarkttraditie met paardenmarkt, warenmarkt van meerdere kilometers, eetkramen en kermis.",
    imageUrl: images.market,
    startDateTime: "2026-10-20T06:00:00+02:00",
    endDateTime: "2026-10-20T17:00:00+02:00",
    locationName: "Centrum Zuidlaren",
    address: "Marktstraat 1, Zuidlaren",
    category: "markt",
    typeTags: ["Buiten", "Paardenmarkt", "Kermis"],
    organizerName: "Gemeente Tynaarlo",
    sourceUrl: "https://www.tynaarlo.nl/evenementen/zuidlaardermarkt-2026",
    indoorOutdoor: "Buiten",
    expectedVisitors: "Tienduizenden bij normale omstandigheden",
    sourceQuality: "Bevestigd"
  },
  {
    id: "vossenjacht-zuidlaren-2026",
    title: "Vossenjacht",
    shortDescription: "Kinderen zoeken verstopte vossen in het centrum met een stempelkaart.",
    longDescription: "Kinderevenement waarbij kinderen met een stempelkaart op zoek gaan naar verstopte vossen in het centrum. Geschikt voor kinderen van 3 t/m 12 jaar.",
    imageUrl: images.children,
    startDateTime: "2026-10-30T18:00:00+01:00",
    endDateTime: "2026-10-30T20:00:00+01:00",
    locationName: "Centrum Zuidlaren",
    category: "kinderen",
    typeTags: ["Buiten", "Familie", "Avond"],
    organizerName: "Activiteitencommissie Zuidlaren",
    sourceUrl: "https://naarzuidlaren.nl/evenementen/vossenjacht/",
    indoorOutdoor: "Buiten",
    expectedVisitors: "100-500 kinderen/begeleiders",
    sourceQuality: "Bevestigd, datumconflict"
  },
  {
    id: "halloween-horrortocht-zuidlaren-2026",
    title: "Halloween Horrortocht Zuidlaren",
    shortDescription: "Halloween-/horrortocht op het Lentis-terrein in de avond.",
    longDescription: "Halloween-/horrortocht op het Lentis-terrein. Eerdere editie werkte met horrorpersonages in het bos, tijdsblokken en start/eindpunt bij horeca.",
    imageUrl: images.halloween,
    startDateTime: "2026-10-30T19:00:00+01:00",
    endDateTime: "2026-10-30T23:00:00+01:00",
    locationName: "Lentis-terrein, Zuidlaren",
    category: "cultuur",
    typeTags: ["Buiten", "Halloween", "Avond"],
    organizerName: "Activiteitencommissie Zuidlaren",
    sourceUrl: "https://www.tynaarlo.nl/vergunningen/kalender-aangemelde-evenementen",
    indoorOutdoor: "Buiten",
    expectedVisitors: "300-1.000 deelnemers/toeschouwers",
    sourceQuality: "Datum bevestigd, detailprogramma volgt"
  },
  {
    id: "sinterklaasintocht-zuidlaren-2026",
    title: "Sinterklaasintocht Zuidlaren",
    shortDescription: "Publieke intocht van Sinterklaas vanaf haven richting centrum.",
    longDescription: "Publieke intocht van Sinterklaas in Zuidlaren, van haven naar centrum. Detailprogramma voor 2026 volgt waarschijnlijk later.",
    imageUrl: images.sinterklaas,
    startDateTime: "2026-11-14T14:00:00+01:00",
    endDateTime: "2026-11-14T16:00:00+01:00",
    locationName: "Haven en centrum Zuidlaren",
    category: "kinderen",
    typeTags: ["Buiten", "Familie", "Sinterklaas"],
    organizerName: "Lokale activiteitencommissie",
    sourceUrl: "https://www.tynaarlo.nl/vergunningen/kalender-aangemelde-evenementen",
    indoorOutdoor: "Buiten",
    expectedVisitors: "500-2.000 bezoekers",
    sourceQuality: "Datum bevestigd, programma volgt"
  },
  {
    id: "zuidlaarder-kerst-2026",
    title: "Zuidlaarder Kerst",
    shortDescription: "Kerstweekend met markt, sfeer en familieactiviteiten bij De Vlindertuin.",
    longDescription: "Kerstweekend in Zuidlaren. Eerdere editie had intocht van de Kerstman, Santarun en kerstmarkt met circa 40 kramen; 2026-programma volgt.",
    imageUrl: images.christmas,
    startDateTime: "2026-12-18T17:00:00+01:00",
    endDateTime: "2026-12-20T17:00:00+01:00",
    locationName: "Brinkje bij De Vlindertuin",
    category: "markt",
    typeTags: ["Buiten", "Kerstmarkt", "Familie"],
    organizerName: "Naar Zuidlaren / lokale ondernemers",
    sourceUrl: "https://www.tynaarlo.nl/vergunningen/kalender-aangemelde-evenementen",
    indoorOutdoor: "Buiten",
    expectedVisitors: "1.000-5.000 bezoekers",
    sourceQuality: "Datum bevestigd, programma volgt"
  },
  {
    id: "zondagmiddag-live-muziek-grand-cafe-monitor-21-juni-2026",
    title: "Zondagmiddag live muziek Grand Cafe",
    shortDescription: "Monitor-item voor zondagmiddag livemuziek bij Grand Cafe Zuidlaren na juni.",
    longDescription:
      "Grand Cafe publiceert zondagmiddag livemuziek vaak kortcyclisch. Deze kaart markeert de reeks als monitor-item zodat latere artiesten en exacte edities kunnen worden aangevuld.",
    imageUrl: images.music,
    startDateTime: "2026-06-21T16:00:00+02:00",
    endDateTime: "2026-06-21T19:00:00+02:00",
    locationName: "Grand Cafe Zuidlaren",
    address: "De Millystraat 8, Zuidlaren",
    category: "muziek",
    typeTags: ["Monitor", "Binnen", "Horeca"],
    organizerName: "Grand Cafe Zuidlaren",
    sourceUrl: "https://grandcafezuidlaren.nl/agenda/",
    indoorOutdoor: "Binnen",
    expectedVisitors: "50-150 bezoekers",
    sourceQuality: "Monitor-item, datum indicatief"
  },
  {
    id: "open-muziek-podium-grand-cafe-2-juli-2026",
    title: "Open Muziek Podium",
    shortDescription: "Open podium voor muzikanten en publiek in Grand Cafe Zuidlaren.",
    longDescription: "Afgeleide eerste-donderdag-datum voor het terugkerende Open Muziek Podium bij Grand Cafe Zuidlaren.",
    imageUrl: images.music,
    startDateTime: "2026-07-02T20:00:00+02:00",
    endDateTime: "2026-07-02T23:30:00+02:00",
    locationName: "Grand Cafe Zuidlaren",
    address: "De Millystraat 8, Zuidlaren",
    category: "muziek",
    typeTags: ["Monitor", "Binnen", "Open podium"],
    organizerName: "Grand Cafe Zuidlaren",
    sourceUrl: "https://grandcafezuidlaren.nl/nieuws/nieuw-open-muziek-podium/",
    indoorOutdoor: "Binnen",
    expectedVisitors: "30-120 bezoekers/deelnemers",
    sourceQuality: "Monitor-item, reeks bevestigd"
  },
  {
    id: "zuidlaarder-muzieknacht-monitor-2026",
    title: "Zuidlaarder Muzieknacht",
    shortDescription: "Monitor-item voor de jaarlijkse muziekavond op meerdere horecalocaties in het centrum.",
    longDescription:
      "Jaarlijkse muziekavond/-nacht met live muziek en dj's op meerdere horecalocaties. De 2026-editie is nog niet hard gepubliceerd; deze kaart gebruikt een indicatieve zaterdag in juli.",
    imageUrl: images.festival,
    startDateTime: "2026-07-11T16:00:00+02:00",
    endDateTime: "2026-07-12T01:00:00+02:00",
    locationName: "Centrum Zuidlaren",
    category: "muziek",
    typeTags: ["Monitor", "Horeca", "Live muziek"],
    organizerName: "Lokale horeca/centrumondernemers",
    sourceUrl: "https://www.oostermoer.info/nieuws/algemeen/101483/muziek-op-zes-locaties-tijdens-zuidlaarder-muzieknacht",
    indoorOutdoor: "Gemengd",
    expectedVisitors: "Enkele honderden tot 1.500+ bezoekers",
    sourceQuality: "Monitor-item, 2026-datum indicatief"
  },
  {
    id: "open-muziek-podium-grand-cafe-6-augustus-2026",
    title: "Open Muziek Podium",
    shortDescription: "Open podium voor muzikanten en publiek in Grand Cafe Zuidlaren.",
    longDescription: "Afgeleide eerste-donderdag-datum voor het terugkerende Open Muziek Podium bij Grand Cafe Zuidlaren.",
    imageUrl: images.music,
    startDateTime: "2026-08-06T20:00:00+02:00",
    endDateTime: "2026-08-06T23:30:00+02:00",
    locationName: "Grand Cafe Zuidlaren",
    address: "De Millystraat 8, Zuidlaren",
    category: "muziek",
    typeTags: ["Monitor", "Binnen", "Open podium"],
    organizerName: "Grand Cafe Zuidlaren",
    sourceUrl: "https://grandcafezuidlaren.nl/nieuws/nieuw-open-muziek-podium/",
    indoorOutdoor: "Binnen",
    expectedVisitors: "30-120 bezoekers/deelnemers",
    sourceQuality: "Monitor-item, reeks bevestigd"
  },
  {
    id: "open-muziek-podium-grand-cafe-3-september-2026",
    title: "Open Muziek Podium",
    shortDescription: "Open podium voor muzikanten en publiek in Grand Cafe Zuidlaren.",
    longDescription: "Afgeleide eerste-donderdag-datum voor het terugkerende Open Muziek Podium bij Grand Cafe Zuidlaren.",
    imageUrl: images.music,
    startDateTime: "2026-09-03T20:00:00+02:00",
    endDateTime: "2026-09-03T23:30:00+02:00",
    locationName: "Grand Cafe Zuidlaren",
    address: "De Millystraat 8, Zuidlaren",
    category: "muziek",
    typeTags: ["Monitor", "Binnen", "Open podium"],
    organizerName: "Grand Cafe Zuidlaren",
    sourceUrl: "https://grandcafezuidlaren.nl/nieuws/nieuw-open-muziek-podium/",
    indoorOutdoor: "Binnen",
    expectedVisitors: "30-120 bezoekers/deelnemers",
    sourceQuality: "Monitor-item, reeks bevestigd"
  },
  {
    id: "open-muziek-podium-grand-cafe-1-oktober-2026",
    title: "Open Muziek Podium",
    shortDescription: "Open podium voor muzikanten en publiek in Grand Cafe Zuidlaren.",
    longDescription: "Afgeleide eerste-donderdag-datum voor het terugkerende Open Muziek Podium bij Grand Cafe Zuidlaren.",
    imageUrl: images.music,
    startDateTime: "2026-10-01T20:00:00+02:00",
    endDateTime: "2026-10-01T23:30:00+02:00",
    locationName: "Grand Cafe Zuidlaren",
    address: "De Millystraat 8, Zuidlaren",
    category: "muziek",
    typeTags: ["Monitor", "Binnen", "Open podium"],
    organizerName: "Grand Cafe Zuidlaren",
    sourceUrl: "https://grandcafezuidlaren.nl/nieuws/nieuw-open-muziek-podium/",
    indoorOutdoor: "Binnen",
    expectedVisitors: "30-120 bezoekers/deelnemers",
    sourceQuality: "Monitor-item, reeks bevestigd"
  },
  {
    id: "horeca-muziekprogramma-zuidlaardermarktweek-monitor-2026",
    title: "Horeca- en muziekprogramma Zuidlaardermarktweek",
    shortDescription: "Monitor-item voor horeca, live muziek en uitgaan rond de Zuidlaardermarktweek.",
    longDescription:
      "Naast markt en kermis is er traditioneel een uitgebreid horeca- en muziekprogramma in het centrum. Details per horecalocatie volgen later.",
    imageUrl: images.cafe,
    startDateTime: "2026-10-16T20:00:00+02:00",
    endDateTime: "2026-10-21T01:00:00+02:00",
    locationName: "Centrum Zuidlaren",
    category: "muziek",
    typeTags: ["Monitor", "Marktweek", "Horeca"],
    organizerName: "Stichting Evenementen Zuidlaardermarkt en lokale horeca",
    sourceUrl: "https://www.evenementenzuidlaardermarkt.nl/",
    indoorOutdoor: "Gemengd",
    expectedVisitors: "Sterk wisselend per locatie",
    sourceQuality: "Monitor-item, detailprogramma volgt"
  },
  {
    id: "open-muziek-podium-grand-cafe-5-november-2026",
    title: "Open Muziek Podium",
    shortDescription: "Open podium voor muzikanten en publiek in Grand Cafe Zuidlaren.",
    longDescription: "Afgeleide eerste-donderdag-datum voor het terugkerende Open Muziek Podium bij Grand Cafe Zuidlaren.",
    imageUrl: images.music,
    startDateTime: "2026-11-05T20:00:00+01:00",
    endDateTime: "2026-11-05T23:30:00+01:00",
    locationName: "Grand Cafe Zuidlaren",
    address: "De Millystraat 8, Zuidlaren",
    category: "muziek",
    typeTags: ["Monitor", "Binnen", "Open podium"],
    organizerName: "Grand Cafe Zuidlaren",
    sourceUrl: "https://grandcafezuidlaren.nl/nieuws/nieuw-open-muziek-podium/",
    indoorOutdoor: "Binnen",
    expectedVisitors: "30-120 bezoekers/deelnemers",
    sourceQuality: "Monitor-item, reeks bevestigd"
  },
  {
    id: "los-kunst-cultuurfestival-lint-van-licht-monitor-2026",
    title: "LOS Kunst & Cultuurfestival / Lint van Licht",
    shortDescription: "Monitor-item voor kunst, cultuur, muziek en theater in het centrum van Zuidlaren.",
    longDescription:
      "Monitor-item voor een mogelijke late-novembereditie van LOS Kunst & Cultuurfestival / Lint van Licht met kunstroute, podiumprogramma, kinderactiviteiten, muziek, poezie en theater.",
    imageUrl: images.art,
    startDateTime: "2026-11-27T16:00:00+01:00",
    endDateTime: "2026-11-27T23:00:00+01:00",
    locationName: "Centrum Zuidlaren",
    category: "cultuur",
    typeTags: ["Monitor", "Kunst", "Cultuur"],
    organizerName: "Stichting LOS / cultuurpartners",
    sourceUrl: "https://cultuurindesteigers.nl/",
    indoorOutdoor: "Gemengd",
    expectedVisitors: "200-800 bezoekers",
    sourceQuality: "Monitor-item, 2026-datum indicatief"
  },
  {
    id: "open-muziek-podium-grand-cafe-3-december-2026",
    title: "Open Muziek Podium",
    shortDescription: "Open podium voor muzikanten en publiek in Grand Cafe Zuidlaren.",
    longDescription: "Afgeleide eerste-donderdag-datum voor het terugkerende Open Muziek Podium bij Grand Cafe Zuidlaren.",
    imageUrl: images.music,
    startDateTime: "2026-12-03T20:00:00+01:00",
    endDateTime: "2026-12-03T23:30:00+01:00",
    locationName: "Grand Cafe Zuidlaren",
    address: "De Millystraat 8, Zuidlaren",
    category: "muziek",
    typeTags: ["Monitor", "Binnen", "Open podium"],
    organizerName: "Grand Cafe Zuidlaren",
    sourceUrl: "https://grandcafezuidlaren.nl/nieuws/nieuw-open-muziek-podium/",
    indoorOutdoor: "Binnen",
    expectedVisitors: "30-120 bezoekers/deelnemers",
    sourceQuality: "Monitor-item, reeks bevestigd"
  }
];
